[server]
headless = true
address = "localhost"
port = 8502
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FAFAFA"
font = "sans serif"

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname)s %(message)s"

[browser]
gatherUsageStats = false